wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
batch_size:
  desc: null
  value: 128
test_batch_size:
  desc: null
  value: 10
